#!/usr/bin/env python3
"""Generate a Lean decode-faithfulness artifact from an M1 top-level witness.

Reads a `lnp64_top_m1_refinement_witness_v1` JSON artifact (produced by
scripts/run_rtl_top_program_smoke.sh) and emits Lean `example`s proving, with the
kernel `decide` tactic (no `native_decide`, no axioms), that the
actually-emitted RTL packed bit vectors decode -- under the Lean packed-bit
decoders in `Lnp64.M1Transition` -- to exactly the projection field values, op
tag, and status tag recorded in the witness.

The emitted snippet is concatenated after `formal/M1TransitionInvariantModel.lean`
(the model has no lakefile and is checked standalone), so every name resolves in
the `Lnp64.M1Transition` namespace. This is the first artifact that connects the
*emitted* RTL bit vectors to the *Lean* packed-bit model; it covers the packed
field/op/status decode layer. The modeled-rights existential predicates and the
`RtlM1RefinementStep` existential remain executable/Python-mirrored and are
documented as the remaining T4 gap.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WITNESS = ROOT / "build/lnp64-top-m1-refinement-witness.json"

WITNESS_SCHEMA = "lnp64_top_m1_refinement_witness_v1"

COMMIT_OP_BY_VALUE = {
    1: "CommitOp.capDup",
    2: "CommitOp.capSend",
    3: "CommitOp.capRecv",
    4: "CommitOp.capRevoke",
    5: "CommitOp.rejectStale",
    6: "CommitOp.push",
    7: "CommitOp.pull",
    8: "CommitOp.rejectFull",
    9: "CommitOp.capDupDenied",
    10: "CommitOp.objectCreate",
}
COMMIT_STATUS_BY_VALUE = {
    0: "CommitStatus.ok",
    1: "CommitStatus.eperm",
    11: "CommitStatus.eagain",
    122: "CommitStatus.erevoked",
}


def fail(message: str) -> str:
    raise SystemExit(f"gen_m1_witness_lean failed: {message}")


def conj(clauses: list[str]) -> str:
    return "\n      /\\ ".join(clauses)


def field_clauses(bits_hex: str, fields: dict, layout: str) -> list[str]:
    clauses = []
    for name, value in fields.items():
        if not isinstance(value, int) or value < 0:
            fail(f"field {name} has non-natural value {value!r}")
        clauses.append(f'packedLayoutFieldValue 0x{bits_hex} "{name}" {layout} = some {value}')
    return clauses


def tag_clauses(bits_hex: str, op: int, status: int, layout: str) -> list[str]:
    if op not in COMMIT_OP_BY_VALUE:
        fail(f"unknown op value {op}")
    if status not in COMMIT_STATUS_BY_VALUE:
        fail(f"unknown status value {status}")
    return [
        f"packedCommitOpFromLayout 0x{bits_hex} {layout} = some {COMMIT_OP_BY_VALUE[op]}",
        f"packedCommitStatusFromLayout 0x{bits_hex} {layout} = some {COMMIT_STATUS_BY_VALUE[status]}",
    ]


def emit_example(name: str, clauses: list[str]) -> str:
    body = conj(clauses)
    return (
        f"open Lnp64.M1Transition in\n"
        f"example :\n"
        f"      {body} := by\n"
        f"  decide\n"
    )


def main() -> int:
    witness_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_WITNESS
    if not witness_path.exists():
        fail(f"missing witness artifact {witness_path}")
    artifact = json.loads(witness_path.read_text(encoding="utf-8"))
    if artifact.get("schema") != WITNESS_SCHEMA:
        fail(f"unexpected witness schema {artifact.get('schema')!r}")

    records = artifact.get("records")
    if not isinstance(records, list) or not records:
        fail("witness artifact has no records")

    commit_layout = "rtlM1CommitPackedLayout"
    state_layout = "rtlM1StateProjectionPackedLayout"

    out: list[str] = []
    out.append("/- GENERATED by scripts/gen_m1_witness_lean.py -- do not edit by hand. -/")
    out.append("/- Decode-faithfulness of emitted lnp64_top M1 witness bits against the")
    out.append("   Lnp64.M1Transition packed-bit decoders, proved with kernel `decide`. -/")
    out.append("set_option exponentiation.threshold 4096")
    out.append("set_option maxRecDepth 4096")
    out.append("")

    for record in records:
        idx = record["index"]
        commit = record["commit"]
        pre = record["pre_state"]
        post = record["post_state"]
        op = record["op"]
        status = record["status"]

        commit_clauses = tag_clauses(record["commit_bits"], op, status, commit_layout)
        commit_clauses += field_clauses(record["commit_bits"], commit, commit_layout)
        out.append(emit_example(f"m1_witness_commit_{idx}", commit_clauses))

        pre_clauses = tag_clauses(record["pre_state_bits"], op, status, state_layout)
        pre_clauses += field_clauses(record["pre_state_bits"], pre, state_layout)
        out.append(emit_example(f"m1_witness_pre_{idx}", pre_clauses))

        post_clauses = tag_clauses(record["post_state_bits"], op, status, state_layout)
        post_clauses += field_clauses(record["post_state_bits"], post, state_layout)
        out.append(emit_example(f"m1_witness_post_{idx}", post_clauses))

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
