#!/usr/bin/env python3
"""Generate a Lean decode-faithfulness artifact from an M14 scheduler witness.

Reads a `lnp64_m14_domain_refinement_witness_v1` JSON artifact (produced by
scripts/check_rtl_m14_typed_commit_trace.py) and emits Lean `example`s proving,
with the kernel `decide` tactic (no `native_decide`, no axioms), that the
actually-emitted M14 packed commit/state bit vectors decode -- under the
`Lnp64.M14Transition` packed-bit decoders -- to exactly the recorded projection
field values.

The emitted snippet is concatenated after `formal/M14TransitionInvariantModel.lean`
(checked standalone, no lakefile), so every name resolves in the
`Lnp64.M14Transition` namespace. Every M14 field is a plain scalar/bool slice, so
this covers the full packed field decode for both records per commit.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WITNESS = ROOT / "build/lnp64-m14-domain-refinement-witness.json"
WITNESS_SCHEMA = "lnp64_m14_domain_refinement_witness_v1"


def fail(message: str) -> str:
    raise SystemExit(f"gen_m14_witness_lean failed: {message}")


def field_clauses(bits_hex: str, fields: dict, layout: str) -> list[str]:
    clauses = []
    for name, value in fields.items():
        if not isinstance(value, int) or value < 0:
            fail(f"field {name} has non-natural value {value!r}")
        clauses.append(f'packedLayoutFieldValue 0x{bits_hex} "{name}" {layout} = some {value}')
    return clauses


def emit_example(clauses: list[str]) -> str:
    body = "\n      /\\ ".join(clauses)
    return (
        "open Lnp64.M14Transition in\n"
        "example :\n"
        f"      {body} := by\n"
        "  decide\n"
    )


def main() -> int:
    witness_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_WITNESS
    if not witness_path.exists():
        fail(f"missing witness artifact {witness_path}")
    artifact = json.loads(witness_path.read_text(encoding="utf-8"))
    if artifact.get("schema") != WITNESS_SCHEMA:
        fail(f"unexpected witness schema {artifact.get('schema')!r}")

    records = artifact.get("records")
    if not isinstance(records, list) or not records:
        fail("witness artifact has no records")

    commit_layout = "rtlM14CommitPackedLayout"
    state_layout = "rtlM14StateProjectionPackedLayout"

    out: list[str] = []
    out.append("/- GENERATED by scripts/gen_m14_witness_lean.py -- do not edit by hand. -/")
    out.append("/- Decode-faithfulness of emitted M14 scheduler witness bits against the")
    out.append("   Lnp64.M14Transition packed-bit decoders, proved with kernel `decide`. -/")
    out.append("set_option exponentiation.threshold 4096")
    out.append("set_option maxRecDepth 4096")
    out.append("")

    for record in records:
        commit = record["commit"]
        state = record["state"]
        out.append(emit_example(field_clauses(record["commit_bits"], commit, commit_layout)))
        out.append(emit_example(field_clauses(record["state_bits"], state, state_layout)))

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
